name: Build and Deploy 
on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [ main ]
    tags: ["v*"]
  pull_request:
    branches: [ main ] 
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: rg.fr-par.scw.cloud/ns-solagratia-prd/nestor

      - name: Login to private registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/ns-solagratia-prd
          username: ${{ secrets.SCW_USERNAME }}
          password: ${{ secrets.SCW_SECRET_KEY }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}